spring:
  application:
    name: hello-spring-cloud-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084

#zipkin默认端口
server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#zipkin2.80版本不支持以下配置（没有以下配置）
management:
  metrics:
    web:
      server:
        auto-time-requests: false